PLANA-130-Todo
NohSungwoo/Plana pull request #28
Opened 2024-12-10 12:50 UTC by NohSungwoo

## 변경 목적
- Todo 기능 추가

## 변경 사항
- Add TodoListView
- Add TodoDetailView
- Add TodoStatusUpdateView
- Add SubTodoView
- Add SubTodoStatusView
- Add TodoSetListView
- Add TodoSetDetailView

2024-12-10 13:23 UTC, ChoiWheatley requested changes

2024-12-10 13:23 UTC, ChoiWheatley commented on memos/serializers.py
> -    memo_set = s.PrimaryKeyRelatedField(read_only=True)
`read_only=True`를 적게되면 Todo 생성시 memo를 같이 생성할 수 없습니다. 목요일에 다시 이야기 나눠봅시다.

2024-12-10 13:30 UTC, ChoiWheatley commented on memos/serializers.py
> -    memo_set = s.PrimaryKeyRelatedField(read_only=True)
현재 develop 브랜치의 `MemoDetailSerializer.memo_set`은 `queryset=MemoSet.objects.all()` 로 변경되어 있습니다. 아래 두 명령어를 실행시켜 develop 브랜치의 수정사항을 병합해주시기 바랍니다:

```sh
git fetch -ap && git merge origin/develop
```

2024-12-14 01:38 UTC, ChoiWheatley commented on users/views.py
> +
SignUp API와 관련한 수정은 Todo와 큰 관련성이 없어 별도의 PR로 제안되는 것이 좋습니다. 이 변경사항에 의존하는 다른 브랜치와 충돌이 일어날 가능성이 생기기 때문입니다 (이 코드를 복사,붙여넣기 해야하기 때문)

2024-12-14 01:41 UTC, ChoiWheatley requested changes

2024-12-14 01:41 UTC, ChoiWheatley commented on calendars/models.py
> +        default=1,
default를 삭제해야 합니다.

2024-12-24 12:58 UTC, NohSungwoo commented on calendars/models.py
> +        default=1,
삭제완료

2024-12-24 12:59 UTC, ChoiWheatley approved these changes
LGTM

2024-12-24 12:59 UTC, merged